/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 21-янв-2024 12:47:14 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Sequences */

CREATE SEQUENCE bi_id_seq
    INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;
;


/* Create Tables */

CREATE TABLE bi_channel
(
    id_channel integer NOT NULL,
    id_bi integer NOT NULL
)
;

CREATE TABLE bi_channels_enum
(
    id integer NOT NULL,	-- Идентификатор канала
    name varchar(50) NOT NULL	-- Название канала
)
;

CREATE TABLE bi_feelings_enum
(
    id integer NOT NULL,	-- Идентификатор эмоции
    name varchar(150) NOT NULL	-- наименование эмоции
)
;

CREATE TABLE bi_in_cj_step
(
    id integer NOT NULL,	-- идентификатор записи, первичный ключ
    id_cj_step integer NOT NULL,	-- идентификатор шага CJ
    "order" integer NOT NULL,
    id_bi integer NULL
)
;

CREATE TABLE bi_link
(
    id integer NOT NULL,
    url varchar(4000) NOT NULL,	-- URL Документа или макета
    descr varchar(50) NULL,	-- Описание
    id_bi integer NOT NULL,
    type_id integer NOT NULL
)
;

CREATE TABLE bi_participant_enum
(
    id integer NOT NULL,	-- идентификатор участника
    name varchar(128) NOT NULL	-- наименование участника взаимодействия
)
;

CREATE TABLE bi_participants
(
    id integer NOT NULL,	-- Идентификатор записи
    id_type integer NOT NULL,	-- тип участника
    descr varchar(255) NULL,	-- описание участника
    id_bi integer NOT NULL,	-- идентификатор BI
    value varchar(4000) NOT NULL	-- Ценность для участника BI
)
;

CREATE TABLE bi_relations
(
    id integer NOT NULL,	-- Идентификатор записи
    id_bi_source integer NOT NULL,	--  Ссылка на предыдущий BI
    name varchar(150) NOT NULL,	-- наиемнование перехода
    descr varchar(4000) NULL,	-- описание перехода
    id_bi_target integer NOT NULL,	-- Ссылка на следующий BI
    id_cj integer NOT NULL	-- Идентификатор CJ в котором переход
)
;

CREATE TABLE bi_status
(
    id integer NOT NULL,	-- Идентификатор
    name varchar(50) NOT NULL,	-- имя статуса
    descr varchar(255) NULL	-- описание статуса
)
;

CREATE TABLE business_iteraction
(
    id integer NOT NULL,	-- Идентификатор BI
    unique_ident varchar(50) NOT NULL,	-- Уникальные идентификатор BI (цифробуквенный). Формируется как префикс "BI." и значение из сиквенса BI_id_seq, с нулями дополненными слева до 8 символов.
    name varchar(255) NOT NULL,	-- Наименование BI
    descr varchar(4000) NULL,	-- Описание BI
    dt_updated timestamp without time zone NOT NULL,	-- дата последнего изменения
    dt_created timestamp without time zone NOT NULL,	-- дата создания
    b_communal boolean NOT NULL   DEFAULT false,	-- вид -коммунальный/некоммунальный
    touchpoints varchar(4000) NULL,	-- точки взаимодействия
    feelings integer NOT NULL,	-- Чувства клиента, значения из справочника
    ea_guid varchar(50) NULL,	-- идентификатор из Sparx EA
    id_product_ext integer NOT NULL,	-- идентификатор продукта-владельца
    owner_role varchar(50) NULL,	-- Владелец-роль
    status_id integer NOT NULL,	-- статус ЖЦ
    client_scenario varchar(4000) NOT NULL,	--  Клиентский сценарий
    ucs_reaction varchar(4000) NOT NULL,	-- описание реакции ЕКП
    b_target boolean NOT NULL,
    b_draft boolean NOT NULL
)
;

CREATE TABLE cj
(
    id integer NOT NULL,	-- Идентификатор клиентского пути
    name varchar(100) NOT NULL,	-- Наименование клиентского пути
    user_portrait varchar(4000) NULL,	-- Потртер пользователя
    last_updated timestamp without time zone NULL,	-- Дата время последнего обновления
    b_draft boolean NOT NULL   DEFAULT true,	-- признак черновика
    id_author integer NOT NULL,	-- Автор
    id_product_ext integer NOT NULL	-- Продукт к которому относится клиенский путь
)
;

CREATE TABLE cj_steps
(
    id integer NOT NULL,	-- Идентификатор шага
    "order" integer NOT NULL,	-- Порядковый номер шага
    name varchar(50) NOT NULL,	-- Наименование шага
    id_cj integer NULL	-- внешний ключ на идентификатор CJ
)
;

CREATE TABLE link_enum
(
    id integer NOT NULL,
    type varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX ixfk_bi_channel_bi_channels_enum ON bi_channel (id_channel ASC)
;

CREATE INDEX ixfk_bi_channel_business_iteraction ON bi_channel (id_bi ASC)
;

ALTER TABLE bi_channels_enum ADD CONSTRAINT pk_bi_channels_enum
    PRIMARY KEY (id)
;

ALTER TABLE bi_feelings_enum ADD CONSTRAINT pk_bi_feelings_enum
    PRIMARY KEY (id)
;

ALTER TABLE bi_in_cj_step ADD CONSTRAINT pk_b_iin_cj_step
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_b_iin_cj_step_business_iteraction ON bi_in_cj_step (id_bi ASC)
;

CREATE INDEX ixfk_b_iin_cj_step_cj_steps ON bi_in_cj_step (id_cj_step ASC)
;

ALTER TABLE bi_link ADD CONSTRAINT pk_bilink
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_bi_link_business_iteraction ON bi_link (id_bi ASC)
;

CREATE INDEX ixfk_bi_link_link_enum ON bi_link (type_id ASC)
;

ALTER TABLE bi_participant_enum ADD CONSTRAINT pk_bi_participant_enum
    PRIMARY KEY (id)
;

ALTER TABLE bi_participants ADD CONSTRAINT pk_bi_participants
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_bi_participants_bi_participant_enum ON bi_participants (id_type ASC)
;

CREATE INDEX ixfk_bi_participants_business_iteraction ON bi_participants (id_bi ASC)
;

ALTER TABLE bi_relations ADD CONSTRAINT pk_bi_inputs_outputs
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_bi_inputs_outputs_business_iteraction ON bi_relations (id_bi_source ASC)
;

CREATE INDEX ixfk_bi_inputs_outputs_business_iteraction_02 ON bi_relations (id_bi_target ASC)
;

CREATE INDEX ixfk_bi_relations_b_iin_cj_step ON bi_relations (id_bi_source ASC)
;

CREATE INDEX ixfk_bi_relations_b_iin_cj_step_02 ON bi_relations (id_bi_target ASC)
;

CREATE INDEX ixfk_bi_relations_cj ON bi_relations (id_cj ASC)
;

ALTER TABLE bi_status ADD CONSTRAINT pk_bi_status
    PRIMARY KEY (id)
;

ALTER TABLE business_iteraction ADD CONSTRAINT pk_business_iteraction
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_business_iteraction_bi_feelings_enum ON business_iteraction (feelings ASC)
;

CREATE INDEX ixfk_business_iteraction_bi_status ON business_iteraction (status_id ASC)
;

ALTER TABLE cj ADD CONSTRAINT pk_cj
    PRIMARY KEY (id)
;

ALTER TABLE cj
    ADD CONSTRAINT uniq UNIQUE (name)
;

CREATE INDEX ixfk_cj_product ON cj (id_product_ext ASC)
;

CREATE INDEX ixfk_cj_user_profile ON cj (id_author ASC)
;

ALTER TABLE cj_steps ADD CONSTRAINT pk_cj_steps
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_cj_steps_cj ON cj_steps (id_cj ASC)
;

ALTER TABLE link_enum ADD CONSTRAINT pk_link_enum
    PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE bi_channel ADD CONSTRAINT fk_bi_channel_bi_channels_enum
    FOREIGN KEY (id_channel) REFERENCES bi_channels_enum (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bi_channel ADD CONSTRAINT fk_bi_channel_business_iteraction
    FOREIGN KEY (id_bi) REFERENCES business_iteraction (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE bi_in_cj_step ADD CONSTRAINT fk_b_iin_cj_step_business_iteraction
    FOREIGN KEY (id_bi) REFERENCES business_iteraction (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bi_in_cj_step ADD CONSTRAINT fk_b_iin_cj_step_cj_steps
    FOREIGN KEY (id_cj_step) REFERENCES cj_steps (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE bi_link ADD CONSTRAINT fk_bi_link_business_iteraction
    FOREIGN KEY (id_bi) REFERENCES business_iteraction (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE bi_link ADD CONSTRAINT fk_bi_link_link_enum
    FOREIGN KEY (type_id) REFERENCES link_enum (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bi_participants ADD CONSTRAINT fk_bi_participants_bi_participant_enum
    FOREIGN KEY (id_type) REFERENCES bi_participant_enum (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bi_participants ADD CONSTRAINT fk_bi_participants_business_iteraction
    FOREIGN KEY (id_bi) REFERENCES business_iteraction (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE bi_relations ADD CONSTRAINT fk_bi_relations_b_iin_cj_step
    FOREIGN KEY (id_bi_source) REFERENCES bi_in_cj_step (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bi_relations ADD CONSTRAINT fk_bi_relations_b_iin_cj_step_02
    FOREIGN KEY (id_bi_target) REFERENCES bi_in_cj_step (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bi_relations ADD CONSTRAINT fk_bi_relations_cj
    FOREIGN KEY (id_cj) REFERENCES cj (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE business_iteraction ADD CONSTRAINT fk_business_iteraction_bi_feelings_enum
    FOREIGN KEY (feelings) REFERENCES bi_feelings_enum (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE business_iteraction ADD CONSTRAINT fk_business_iteraction_bi_status
    FOREIGN KEY (status_id) REFERENCES bi_status (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cj_steps ADD CONSTRAINT fk_cj_steps_cj
    FOREIGN KEY (id_cj) REFERENCES cj (id) ON DELETE Cascade ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE bi_channel
	IS 'Сопоставление канала и BI'
;

COMMENT ON TABLE bi_channels_enum
	IS 'Справочник каналов'
;

COMMENT ON COLUMN bi_channels_enum.id
	IS 'Идентификатор канала'
;

COMMENT ON COLUMN bi_channels_enum.name
	IS 'Название канала'
;

COMMENT ON TABLE bi_feelings_enum
	IS 'Справочник чувств и эмоций клиента'
;

COMMENT ON COLUMN bi_feelings_enum.id
	IS 'Идентификатор эмоции'
;

COMMENT ON COLUMN bi_feelings_enum.name
	IS 'наименование эмоции'
;

COMMENT ON TABLE bi_in_cj_step
	IS 'принадлежность BI шагу CJ'
;

COMMENT ON COLUMN bi_in_cj_step.id
	IS 'идентификатор записи, первичный ключ'
;

COMMENT ON COLUMN bi_in_cj_step.id_cj_step
	IS 'идентификатор шага CJ'
;

COMMENT ON TABLE bi_link
	IS 'Ссылки BI на мекеты и документы'
;

COMMENT ON COLUMN bi_link.url
	IS 'URL Документа или макета'
;

COMMENT ON COLUMN bi_link.descr
	IS 'Описание'
;

COMMENT ON TABLE bi_participant_enum
	IS 'Справочник участников взаимодействия'
;

COMMENT ON COLUMN bi_participant_enum.id
	IS 'идентификатор участника'
;

COMMENT ON COLUMN bi_participant_enum.name
	IS 'наименование участника взаимодействия'
;

COMMENT ON TABLE bi_participants
	IS 'Таблица с описанием конкретных участников BI'
;

COMMENT ON COLUMN bi_participants.id
	IS 'Идентификатор записи'
;

COMMENT ON COLUMN bi_participants.id_type
	IS 'тип участника'
;

COMMENT ON COLUMN bi_participants.descr
	IS 'описание участника'
;

COMMENT ON COLUMN bi_participants.id_bi
	IS 'идентификатор BI'
;

COMMENT ON COLUMN bi_participants.value
	IS 'Ценность для участника BI'
;

COMMENT ON TABLE bi_relations
	IS 'Отношения вход выход между BI'
;

COMMENT ON COLUMN bi_relations.id
	IS 'Идентификатор записи'
;

COMMENT ON COLUMN bi_relations.id_bi_source
	IS ' Ссылка на предыдущий BI'
;

COMMENT ON COLUMN bi_relations.name
	IS 'наиемнование перехода'
;

COMMENT ON COLUMN bi_relations.descr
	IS 'описание перехода'
;

COMMENT ON COLUMN bi_relations.id_bi_target
	IS 'Ссылка на следующий BI'
;

COMMENT ON COLUMN bi_relations.id_cj
	IS 'Идентификатор CJ в котором переход'
;

COMMENT ON TABLE bi_status
	IS 'Справочник статусов ЖЦ BI'
;

COMMENT ON COLUMN bi_status.id
	IS 'Идентификатор'
;

COMMENT ON COLUMN bi_status.name
	IS 'имя статуса'
;

COMMENT ON COLUMN bi_status.descr
	IS 'описание статуса'
;

COMMENT ON TABLE business_iteraction
	IS 'Бизнес взаимодействие'
;

COMMENT ON COLUMN business_iteraction.id
	IS 'Идентификатор BI'
;

COMMENT ON COLUMN business_iteraction.unique_ident
	IS 'Уникальные идентификатор BI (цифробуквенный).
Формируется как префикс "BI." и значение из сиквенса BI_id_seq, с нулями дополненными слева до 8 символов.'
;

COMMENT ON COLUMN business_iteraction.name
	IS 'Наименование BI'
;

COMMENT ON COLUMN business_iteraction.descr
	IS 'Описание BI'
;

COMMENT ON COLUMN business_iteraction.dt_updated
	IS 'дата последнего изменения'
;

COMMENT ON COLUMN business_iteraction.dt_created
	IS 'дата создания'
;

COMMENT ON COLUMN business_iteraction.b_communal
	IS 'вид -коммунальный/некоммунальный'
;

COMMENT ON COLUMN business_iteraction.touchpoints
	IS 'точки взаимодействия'
;

COMMENT ON COLUMN business_iteraction.feelings
	IS 'Чувства клиента, значения из справочника'
;

COMMENT ON COLUMN business_iteraction.ea_guid
	IS 'идентификатор из Sparx EA'
;

COMMENT ON COLUMN business_iteraction.id_product_ext
	IS 'идентификатор продукта-владельца'
;

COMMENT ON COLUMN business_iteraction.owner_role
	IS 'Владелец-роль'
;

COMMENT ON COLUMN business_iteraction.status_id
	IS 'статус ЖЦ'
;

COMMENT ON COLUMN business_iteraction.client_scenario
	IS ' Клиентский сценарий'
;

COMMENT ON COLUMN business_iteraction.ucs_reaction
	IS 'описание реакции ЕКП'
;

COMMENT ON TABLE cj
	IS 'Клиентский путь'
;

COMMENT ON COLUMN cj.id
	IS 'Идентификатор клиентского пути'
;

COMMENT ON COLUMN cj.name
	IS 'Наименование клиентского пути'
;

COMMENT ON COLUMN cj.user_portrait
	IS 'Потртер пользователя'
;

COMMENT ON COLUMN cj.last_updated
	IS 'Дата время последнего обновления'
;

COMMENT ON COLUMN cj.b_draft
	IS 'признак черновика'
;

COMMENT ON COLUMN cj.id_author
	IS 'Автор '
;

COMMENT ON COLUMN cj.id_product_ext
	IS 'Продукт к которому относится клиенский путь'
;

COMMENT ON TABLE cj_steps
	IS 'Шаги CJ'
;

COMMENT ON COLUMN cj_steps.id
	IS 'Идентификатор шага'
;

COMMENT ON COLUMN cj_steps."order"
	IS 'Порядковый номер шага '
;

COMMENT ON COLUMN cj_steps.name
	IS 'Наименование шага'
;

COMMENT ON COLUMN cj_steps.id_cj
	IS 'внешний ключ на идентификатор CJ'
;

COMMENT ON TABLE link_enum
	IS 'Типы ссылок на документы'
;
